# Generated by Django 4.1.1 on 2022-10-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1999-04-16'),
            preserve_default=False,
        ),
    ]
